name: Deployment
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: deployment
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build page
        run: npm run build
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/241015634198/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'github-action@scenic-rampart-397810.iam.gserviceaccount.com'
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          path: 'build'
          destination: 'mercenarieshunter.com'
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'minor'