name: Deployment
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build page
        run: npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
      - name: set git commit user.name
        run: git config --global user.name 'github robot'
      - name: set git commit user.email
        run: git config --global user.email 'robot.resume@gmail.com'
      - name: ignore build
        run: git checkout .
      - name: update version number
        run: npm version patch -m "[RELEASE] %s"
      - name: push tag
        run: git push --tag
