name: unit test

on:
 pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.17.3
      uses: actions/setup-node@v3
      with:
        node-version: 14.17.3

    - name: Test
      run: |
        npm install
        npm run test -- --watchAll=false
